mvc-app/BeingDK.ExpenseTracker.Web.FrontEnd/Models/ExpensesReportViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Helpers;
using BeingDK.ExpenseTracker.Data;

namespace BeingDK.ExpenseTracker.Web.FrontEnd.Models
{
    public class Graph
    {
        public string XCoordinate { get; set; }
        public string YCoordinate { get; set; }
    }

    public partial class ExpensesReportViewModel
    {
        public IEnumerable<Expense> Expenses = Enumerable.Empty<Expense>();
        private readonly AppDataContext db = new AppDataContext();
        public string GraphUrl { get; set; }

        [Required]
        public DateTime SelectedMonth { get; set; }

        internal ExpensesReportViewModel Get()
        {
            var month = SelectedMonth.Month;
            var year = SelectedMonth.Year;
            var firstDayOfMonth = new DateTime(year, month, 1);
            var daysInMonth = DateTime.DaysInMonth(year, month);
            var lastDayOfMonth = new DateTime(year, month, daysInMonth);

            Expenses = db.Expenses.Where(x => x.IncurredAt >= firstDayOfMonth && x.IncurredAt <= lastDayOfMonth)
                                  .OrderBy(x => x.IncurredAt)
                                  .ToList();

            var graphData = Expenses.GroupBy(x => x.IncurredAt)
                    .Select(x => new Graph
                    {
                        XCoordinate = x.Key.ToString("dd-MM-yyyy")
                    ,
                        YCoordinate = x.Sum(y => y.Amount).ToString()
                    })
                    .ToList();

            if (graphData != null && graphData.Any())
            {
                var chartWebImage = new Chart(width: 900, height: 500, theme: ChartTheme.Yellow)
                                   .AddTitle("Monthly expenses")
                                   .AddSeries("Default", chartType: "Line",
                                       xValue: graphData, xField: "XCoordinate",
                                       yValues: graphData, yFields: "YCoordinate")
                                   .ToWebImage();

                if (chartWebImage != null)
                {
                    var imagePath = @"images\" + Guid.NewGuid() + ".jpeg";
                    chartWebImage.Save(@"~\" + imagePath);
                    GraphUrl = imagePath;
                }
            }

            return this;
        }
    }
}

mvc-app/BeingDK.ExpenseTracker.Web.FrontEnd/Controllers/ExpensesReportController.cs
using System;
using System.Web.Mvc;
using BeingDK.ExpenseTracker.Web.FrontEnd.Models;

namespace BeingDK.ExpenseTracker.Web.FrontEnd.Controllers
{
    [Authorize]
    public class ExpensesReportController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new ExpensesReportViewModel { SelectedMonth = DateTime.Now });
        }

        [HttpPost]
        public ActionResult Index(ExpensesReportViewModel model)
        {
            return View(model.Get());
        }
    }
}

mvc-app/BeingDK.ExpenseTracker.Web.FrontEnd/Views/ExpensesReport/Index.cshtml
@model BeingDK.ExpenseTracker.Web.FrontEnd.Models.ExpensesReportViewModel

@{
    ViewBag.Title = "Expenses report";
}

<div class="row margin-top-20">
    <div class="col-sm-12">
        @using (Html.BeginForm("Index", "ExpensesReport"))
        {
            @Html.AntiForgeryToken()
            <input type="month" class="month-selector" id="SelectedMonth" name="SelectedMonth"
                   value="@Model.SelectedMonth.ToString("yyyy-MM")" />
            <input type="submit" class="btn btn-primary" value="Go!" />
        }

        @{

            if (!string.IsNullOrWhiteSpace(Model.GraphUrl))
            {
                <img src="@Model.GraphUrl" alt="GRaph" />
            }
        }

        <table class="table">
            <tr>
                <th>
                    Incurred Date
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Description
                </th>
                <th>
                    Category
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Expenses)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IncurredAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpenseCategory.Name)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>